// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pniigbitkmdmwfbnfall.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuaWlnYml0a21kbXdmYm5mYWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTY4MjIsImV4cCI6MjA2MDMzMjgyMn0.hA5BXhp5lxU9HnooR8pY_5wenaFV31E7HITm2fp8zqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);